services:
  nginx:
    build: .
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - ./fishtest:/app/fishtest
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./fishtest.conf:/etc/nginx/sites-available/fishtest.conf:ro
    depends_on:
      # - server6543
      # - server6544
      # - server6545
      - development
    networks:
      - fishtest-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --wiredTigerCacheSizeGB 2.0
    networks:
      - fishtest-network

  development:
    build: .
    command:
      - /bin/sh
      - "-c"
      - "/app/entrypoint.sh"
    ports:
      - "6542:6542"
    volumes:
      - ./fishtest:/app/fishtest

    environment:
      - FISHTEST_URL=http://127.0.0.1
      - FISHTEST_CAPTCHA_SECRET=your-secret-key-here # dev usage only
      - FISHTEST_NN_URL=http://127.0.0.1
    depends_on:
      - mongodb
    networks:
      - fishtest-network
    extra_hosts:
      - "localhost:172.17.0.1"

volumes:
  mongodb_data:

networks:
  fishtest-network:
    driver: bridge
