services:
  fishtest-worker:
    image: ghcr.io/official-stockfish/fishtest-worker:latest
    restart: always
    stop_grace_period: 1m30s
    container_name: fishtest-worker
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    shm_size: '1gb'  # for shared network
    environment:
      - NUM_WORKERS
      - WORKER_ARGS
